# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Chen Li Group"
title:              "Chen Li Group at Xi'an Jiaotong University"
description:        "Chen Li Group is a research group at Xi'an Jiaotong University."


# URL
url:                http://chenli.group
# url:                https://chenligroup.github.io/
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "research"
    href:           "/research"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
#  - name:           "blog"
#    href:           "/blog"
#  - name:           "resources"
#    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
